vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gcc", function() 
    vim.cmd("Git add .")
    vim.cmd("Git commit -a")
end)
vim.keymap.set("n", "<leader>gur", function() 
    vim.cmd("Git push origin " .. vim.fn.system("git branch --show-current 2> /dev/null | tr -d '\n'"))
end)
vim.keymap.set("n", "<leader>gul", function() 
    vim.cmd("Git pull origin " .. vim.fn.system("git branch --show-current 2> /dev/null | tr -d '\n'"))
end)
